name: test_bug_visio
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  freezed_annotation: ^0.14.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^0.14.1
  build_runner: ^2.0.0
  json_serializable: ^4.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.orange.obs.plugins.myplace_svc_mapview
        pluginClass: MapViewPlugin


